### ISSUE TITLE
Cobertura: Error reading file cobertura.ser: null java.io.EOFException: null

### ISSUE THREAD

**Issue by dschveninger** [mojohaus/cobertura-maven-plugin#3]
We are running maven plugin in side jenkins and we are getting the following error. Can you provide me with any ideas to correct this issue.  Thanks in Advance

10:01:44 [INFO] --- cobertura-maven-plugin:2.7:cobertura (default-cli) @ cips-core ---
10:01:44 [INFO] Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
10:01:44 [ERROR] Cobertura: Error reading file C:\jenkins\slaves\at-deployer\workspace\ICD-t__cips-parent__code-coverage-git\cips-parent\cips-core\target\cobertura\cobertura.ser: null
10:01:44 java.io.EOFException: null
10:01:44 	at java.io.ObjectInputStream$BlockDataInputStream.readFully(ObjectInputStream.java:2744) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1979) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370) ~[na:1.7.0_51]
10:01:44 	at java.util.HashMap.readObject(HashMap.java:1184) ~[na:1.7.0_51]
10:01:44 	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source) ~[na:na]
10:01:44 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
10:01:44 	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:500) ~[na:1.7.0_51]
10:01:44 	at net.sourceforge.cobertura.coveragedata.CoverageDataContainer.readObject(CoverageDataContainer.java:321) ~[cobertura-2.1.1.jar:2.1.1]
10:01:44 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[na:na]
10:01:44 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
10:01:44 	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370) ~[na:1.7.0_51]
10:01:44 	at java.util.HashMap.readObject(HashMap.java:1184) ~[na:1.7.0_51]
10:01:44 	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source) ~[na:na]
10:01:44 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
10:01:44 	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:500) ~[na:1.7.0_51]
10:01:44 	at net.sourceforge.cobertura.coveragedata.CoverageDataContainer.readObject(CoverageDataContainer.java:321) ~[cobertura-2.1.1.jar:2.1.1]
10:01:44 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_51]
10:01:44 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_51]
10:01:44 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
10:01:44 	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370) ~[na:1.7.0_51]
10:01:44 	at java.util.HashMap.readObject(HashMap.java:1184) ~[na:1.7.0_51]
10:01:44 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_51]
10:01:44 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_51]
10:01:44 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
10:01:44 	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:500) ~[na:1.7.0_51]
10:01:44 	at net.sourceforge.cobertura.coveragedata.CoverageDataContainer.readObject(CoverageDataContainer.java:321) ~[cobertura-2.1.1.jar:2.1.1]
10:01:44 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_51]
10:01:44 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_51]
10:01:44 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
10:01:44 	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_51]
10:01:44 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370) ~[na:1.7.0_51]
10:01:44 	at net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler.loadCoverageData(CoverageDataFileHandler.java:85) ~[cobertura-2.1.1.jar:2.1.1]
10:01:44 	at net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler.loadCoverageData(CoverageDataFileHandler.java:62) ~[cobertura-2.1.1.jar:2.1.1]
10:01:44 	at net.sourceforge.cobertura.dsl.Cobertura.getProjectDataInstance(Cobertura.java:146) [cobertura-2.1.1.jar:2.1.1]
10:01:44 	at net.sourceforge.cobertura.dsl.Cobertura.report(Cobertura.java:122) [cobertura-2.1.1.jar:2.1.1]
10:01:44 	at net.sourceforge.cobertura.reporting.ReportMain.parseArgumentsAndReport(ReportMain.java:91) [cobertura-2.1.1.jar:2.1.1]
10:01:44 	at net.sourceforge.cobertura.reporting.ReportMain.generateReport(ReportMain.java:141) [cobertura-2.1.1.jar:2.1.1]
10:01:44 	at net.sourceforge.cobertura.reporting.ReportMain.main(ReportMain.java:151) [cobertura-2.1.1.jar:2.1.1]

**Comment by satish-patil** [comment]
I am facing this same issue. Using java 8
java.io.EOFException: null
        at java.io.ObjectInputStream$BlockDataInputStream.readFully(ObjectInputStream.java:2754) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1989) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:501) ~[na:1.8.0_66]
        at java.util.ArrayList.readObject(ArrayList.java:779) ~[na:1.8.0_66]
        at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1900) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) ~[na:1.8.0_66]
        at java.util.HashMap.readObject(HashMap.java:1396) ~[na:1.8.0_66]
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1900) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:501) ~[na:1.8.0_66]
        at net.sourceforge.cobertura.coveragedata.CoverageDataContainer.readObject(CoverageDataContainer.java:321) ~[cobertura-2.1.1.jar:2.1.1]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1900) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) ~[na:1.8.0_66]
        at java.util.HashMap.readObject(HashMap.java:1396) ~[na:1.8.0_66]
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1900) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:501) ~[na:1.8.0_66]
        at net.sourceforge.cobertura.coveragedata.CoverageDataContainer.readObject(CoverageDataContainer.java:321) ~[cobertura-2.1.1.jar:2.1.1]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1900) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) ~[na:1.8.0_66]
        at java.util.HashMap.readObject(HashMap.java:1396) ~[na:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1900) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:501) ~[na:1.8.0_66]
        at net.sourceforge.cobertura.coveragedata.CoverageDataContainer.readObject(CoverageDataContainer.java:321) ~[cobertura-2.1.1.jar:2.1.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1900) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_66]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) ~[na:1.8.0_66]
        at net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler.loadCoverageData(CoverageDataFileHandler.java:85) ~[cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler.loadCoverageData(CoverageDataFileHandler.java:62) ~[cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.dsl.Cobertura.getProjectDataInstance(Cobertura.java:146) [cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.dsl.Cobertura.report(Cobertura.java:122) [cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.reporting.ReportMain.parseArgumentsAndReport(ReportMain.java:91) [cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.reporting.ReportMain.generateReport(ReportMain.java:141) [cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.reporting.ReportMain.main(ReportMain.java:151) [cobertura-2.1.1.jar:2.1.1]

**Comment by yogeshl5481** [comment]
Facing similar issues with jdk1.7.0_55 and apache-maven-3.3.3 in Windows7
Below are plugin details:
1) maven-surefire-plugin : 2.19.1
2) cobertura-maven-plugin :  2.7  (error is same as previous comments in this issue thred)

Found same issues with 2.5.2 as well. log was different.

[ERROR] Cobertura: Error reading file C:\Users\workspace\Documents\Code\maven\owebdev\target\cobertura\cobertura.ser: null
Error: Unable to read from data file C:\Users\workspace\Documents\Code\maven\owebdev\target\cobertura\cobertura.ser

I have close to 8500 classes in project.

cobertura.ser.lock file was present in target\cobertura

Issue does not occur  when I reduce files  to approx to 800

**Comment by MEZk** [comment]
The same error on jdk 1.7.0_95 and maven 3.2.5.

**Comment by NoxFr** [comment]
Facing the same problem...
- cobertura-2.1.1 (cobertura-maven-plugin 2.7)
- surefire 2.12.4
- jdk 1.8.0_92

No workaround found... (more memory allowed, cleaned workspace...)

**Comment by MEZk** [comment]
@NoxFr 
Try to set surefire version to 2.12 (not 2.12.4)

**Comment by NoxFr** [comment]
It seems to work for now with surefire 2.12... (2 builds in a row)
Well... crossing fingers 😄 
I would be interested to know why....
