### ISSUE TITLE
using corbertura-integration-test fails on multi module build with ava.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/TouchCollector

### ISSUE THREAD

**Issue by joshiste** [mojohaus/cobertura-maven-plugin#8]
I have a multi-module build with submodule A and B. B depends on classes from A. 
Both modules have unit and integration-tests.

Configuring the `cobertura-integration-test`-goal for verify leads to failing tests with `java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/TouchCollector`.
Using `cobertura`-goal everything is fine.

I seems the "ordinary" surefire-test-execution in submodule B picks up instrumented classes from a and is missing cobertura on the classpath.

Sample project to reproduce:
https://github.com/joshiste/cobertura-mm-issue

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] cobertura-issue
[INFO] cobertura-issue-a
[INFO] cobertura-issue-b
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building cobertura-issue 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ cobertura-issue ---
[INFO] Deleting /home/johannes/projects/cobertura-mm-issue/target
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19:integration-test (default) @ cobertura-issue ---
[INFO] No tests to run.
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19:verify (default) @ cobertura-issue ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] 
[INFO] >>> cobertura-maven-plugin:2.7:cobertura-integration-test (default) > [cobertura]verify @ cobertura-issue >>>
[INFO] 
[INFO] --- cobertura-maven-plugin:2.7:instrument (default) @ cobertura-issue ---
[INFO] Skipping cobertura mojo for project with packaging type 'pom'
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19:integration-test (default) @ cobertura-issue ---
[INFO] No tests to run.
[INFO] Skipping execution of surefire because it has already been run for this configuration
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19:verify (default) @ cobertura-issue ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] 
[INFO] <<< cobertura-maven-plugin:2.7:cobertura-integration-test (default) < [cobertura]verify @ cobertura-issue <<<
[INFO] 
[INFO] --- cobertura-maven-plugin:2.7:cobertura-integration-test (default) @ cobertura-issue ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building cobertura-issue-a 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ cobertura-issue-a ---
[INFO] Deleting /home/johannes/projects/cobertura-mm-issue/a/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ cobertura-issue-a ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/johannes/projects/cobertura-mm-issue/a/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ cobertura-issue-a ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/johannes/projects/cobertura-mm-issue/a/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ cobertura-issue-a ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/johannes/projects/cobertura-mm-issue/a/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ cobertura-issue-a ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/johannes/projects/cobertura-mm-issue/a/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.19:test (default-test) @ cobertura-issue-a ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.joshiste.cobertura.ATest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in com.joshiste.cobertura.ATest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ cobertura-issue-a ---
[INFO] Building jar: /home/johannes/projects/cobertura-mm-issue/a/target/cobertura-issue-a-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19:integration-test (default) @ cobertura-issue-a ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.joshiste.cobertura.AITest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in com.joshiste.cobertura.AITest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19:verify (default) @ cobertura-issue-a ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] 
[INFO] >>> cobertura-maven-plugin:2.7:cobertura-integration-test (default) > [cobertura]verify @ cobertura-issue-a >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ cobertura-issue-a ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/johannes/projects/cobertura-mm-issue/a/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ cobertura-issue-a ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- cobertura-maven-plugin:2.7:instrument (default) @ cobertura-issue-a ---
[INFO] Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[INFO] Cobertura: Saved information on 1 classes.
[INFO] Cobertura: Saved information on 1 classes.

[INFO] Instrumentation was successful.
[INFO] NOT adding cobertura ser file to attached artifacts list.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ cobertura-issue-a ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/johannes/projects/cobertura-mm-issue/a/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ cobertura-issue-a ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.19:test (default-test) @ cobertura-issue-a ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.joshiste.cobertura.ATest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.252 sec - in com.joshiste.cobertura.ATest
[INFO] Cobertura: Loaded information on 1 classes.
[INFO] Cobertura: Saved information on 1 classes.

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ cobertura-issue-a ---
[INFO] Building jar: /home/johannes/projects/cobertura-mm-issue/a/target/cobertura-issue-a-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19:integration-test (default) @ cobertura-issue-a ---
[INFO] Skipping execution of surefire because it has already been run for this configuration
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19:verify (default) @ cobertura-issue-a ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] 
[INFO] <<< cobertura-maven-plugin:2.7:cobertura-integration-test (default) < [cobertura]verify @ cobertura-issue-a <<<
[INFO] 
[INFO] --- cobertura-maven-plugin:2.7:cobertura-integration-test (default) @ cobertura-issue-a ---
[INFO] Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[INFO] Cobertura: Loaded information on 1 classes.
Report time: 76ms

[INFO] Cobertura Report generation was successful.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building cobertura-issue-b 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ cobertura-issue-b ---
[INFO] Deleting /home/johannes/projects/cobertura-mm-issue/b/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ cobertura-issue-b ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/johannes/projects/cobertura-mm-issue/b/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ cobertura-issue-b ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/johannes/projects/cobertura-mm-issue/b/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ cobertura-issue-b ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/johannes/projects/cobertura-mm-issue/b/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ cobertura-issue-b ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/johannes/projects/cobertura-mm-issue/b/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.19:test (default-test) @ cobertura-issue-b ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.joshiste.cobertura.BTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.007 sec <<< FAILURE! - in com.joshiste.cobertura.BTest
hello(com.joshiste.cobertura.BTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/TouchCollector
	at com.joshiste.cobertura.BTest.hello(BTest.java:11)
Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector
	at com.joshiste.cobertura.BTest.hello(BTest.java:11)


Results :

Tests in error: 
  BTest.hello:11 » NoClassDefFound net/sourceforge/cobertura/coveragedata/TouchC...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] cobertura-issue .................................... SUCCESS [  1.126 s]
[INFO] cobertura-issue-a .................................. SUCCESS [  5.839 s]
[INFO] cobertura-issue-b .................................. FAILURE [  0.664 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.737 s
[INFO] Finished at: 2015-10-29T22:34:40+01:00
[INFO] Final Memory: 22M/257M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test (default-test) on project cobertura-issue-b: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/johannes/projects/cobertura-mm-issue/b/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cobertura-issue-b
```

**Comment by jakub-bochenski** [comment]
This also happens with regular `cobertura:cobertura` goal

When I run `mvn clean cobertura:cobertura -Dcobertura.skip=true` I get a `NoClassDefFoundError/ClassNotFounException` targeting a class defined within the current module.

I think it's the same problem as described here: https://stackoverflow.com/questions/29566281

So depending on your build directory content it will either fail missing one of cobertura's classes or one of module's classes

**Comment by lepirlouit** [comment]
any update for this issue ?
